/*
 * FB B35A1 / Rosetta — coletor relacional isolado 44.21.27
 * Escopo exclusivo: Amigos, Seguindo e Seguidores materializados no DOM.
 * Não navega, não atualiza a página, não usa /friends_all, busca alfabética ou
 * varredura genérica de seções posteriores. O limite é o corredor semântico da
 * coleção ativa e o terminal é comprovado por fronteira ou fundo físico estável.
 */
(function(){
'use strict';
var RELEASE='44.21.27';
var NAME='__FB_B35_EXACT_RELATION_COLLECTOR_442127__';
if(window[NAME]&&window[NAME].release===RELEASE)return;
var CORE_NAME='__FB_B35A1_V43_V42_CORE_EXCEL_UI_FINAL__';
var RESERVED={friends:1,followers:1,following:1,groups:1,watch:1,marketplace:1,reel:1,reels:1,stories:1,events:1,pages:1,gaming:1,messages:1,notifications:1,settings:1,help:1,privacy:1,ads:1,login:1,share:1,search:1,photo:1,photos:1,videos:1,about:1,me:1,'profile.php':1,people:1,hashtag:1,permalink:1,plugins:1,business:1,bookmarks:1,home:1,professional_dashboard:1,latest:1,pages_feed:1,creatorstudio:1,adsmanager:1};
var REL_LABEL={friends:'Amigos',following:'Seguindo',followers:'Seguidores'};

function clean(v){return String(v==null?'':v).replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/\s+/g,' ').trim();}
function norm(v){var s=clean(v).toLowerCase();try{s=s.normalize('NFD').replace(/[\u0300-\u036f]/g,'');}catch(_){ }return s.replace(/[·•|:]+/g,' ').replace(/\s+/g,' ').trim();}
function stripCount(v){return norm(v).replace(/(?:^|\s)\(?\d[\d.,\s]*[kmb]?\)?(?:\s|$)/ig,' ').replace(/\s+/g,' ').trim();}
function visible(el){if(!el||!el.getBoundingClientRect)return false;try{var r=el.getBoundingClientRect(),cs=getComputedStyle(el);return r.width>0&&r.height>0&&cs.display!=='none'&&cs.visibility!=='hidden'&&Number(cs.opacity||1)!==0;}catch(_){return false;}}
function toolNode(el){try{return !!(el&&el.closest&&el.closest('[id^="fb-b35"],[id*="fb-b35"],[data-b35],#fb-b35-unified-v44-panel,#fb-b35a1-raspador-amigos-v29-panel'));}catch(_){return false;}}
function relationFromText(v){var s=stripCount(v);if(/^(?:friends?|amigos?|amizades?|all friends|todos os amigos|todas as amizades)$/.test(s))return 'friends';if(/^(?:following|seguindo)$/.test(s))return 'following';if(/^(?:followers?|seguidores?)$/.test(s))return 'followers';return '';}
function relationFromHref(v){var s=String(v||'').toLowerCase();if(/(?:\/|[?&]sk=)following(?:\/|$|[&#?])/.test(s))return 'following';if(/(?:\/|[?&]sk=)followers(?:\/|$|[&#?])/.test(s))return 'followers';if(/\/friends(?:\/|$|[?#])|[?&]sk=friends(?:&|$)/.test(s))return 'friends';return '';}
function labelOf(el){return clean((el&&el.getAttribute&&((el.getAttribute('aria-label')||el.getAttribute('title'))))||(el&&el.innerText)||(el&&el.textContent)||'');}
function hrefOf(el){return String((el&&el.href)||(el&&el.getAttribute&&el.getAttribute('href'))||'');}
function docTop(el){if(!el)return 0;var r=el.getBoundingClientRect(),sc=document.scrollingElement||document.documentElement;return Number(r.top||0)+Number(window.scrollY||sc.scrollTop||0);}
function docBottom(el){if(!el)return 0;var r=el.getBoundingClientRect(),sc=document.scrollingElement||document.documentElement;return Number(r.bottom||0)+Number(window.scrollY||sc.scrollTop||0);}
function relationHeading(){var nodes=document.querySelectorAll('h1,h2,h3,[role="heading"]'),best=null,bestY=Infinity;for(var i=0;i<nodes.length;i++){var n=nodes[i],r=relationFromText(labelOf(n));if(!visible(n)||toolNode(n)||r!=='friends')continue;var y=docTop(n);if(y>120&&y<bestY){best=n;bestY=y;}}return best;}
function selectedRelationControl(){
  var head=relationHeading(),headY=head?docTop(head):0,nodes=document.querySelectorAll('[role="tab"][aria-selected="true"],a[aria-current="page"],[aria-selected="true"][href]'),best=null,bestScore=-1;
  for(var i=0;i<nodes.length;i++){
    var el=nodes[i];if(!visible(el)||toolNode(el))continue;
    var rel=relationFromText(labelOf(el))||relationFromHref(hrefOf(el));if(!rel)continue;
    var y=docTop(el),score=0;
    if(head&&y>=headY-30)score+=600;if(head&&y<=headY+180)score+=300;
    if(rel!=='friends')score+=160;
    var d=0,p=el;while(p&&p.parentElement){d++;p=p.parentElement;}score+=d;
    if(y>0)score+=Math.min(120,y/20);
    if(score>bestScore){bestScore=score;best={element:el,relation:rel,label:labelOf(el),href:hrefOf(el),documentTop:y,score:score};}
  }
  return best;
}
function forbiddenHeading(v){return /^(?:reels?|photos?|fotos?|check-ins?|checkins?|visitas?|reviews given|avaliacoes|posts?|publicacoes|videos?|grupos?|groups?|likes?|curtidas?)$/.test(stripCount(v));}
function nextBoundary(startY){var nodes=document.querySelectorAll('h1,h2,h3,[role="heading"]'),best=null,bestY=Infinity;for(var i=0;i<nodes.length;i++){var n=nodes[i];if(!visible(n)||toolNode(n)||!forbiddenHeading(labelOf(n)))continue;var y=docTop(n);if(y>startY+60&&y<bestY){best=n;bestY=y;}}return best?{element:best,label:labelOf(best),top:bestY}:null;}
function targetKey(){try{var c=window[CORE_NAME],known=c&&c.state&&String(c.state.pageTargetKey||'');if(known)return known.toLowerCase();}catch(_){ }try{var u=new URL(location.href);if(/\/profile\.php$/i.test(u.pathname)){var id=u.searchParams.get('id');return id?'id:'+id:'';}var p=decodeURIComponent((u.pathname.split('/').filter(Boolean)[0]||''));return p?p.toLowerCase():'';}catch(_){return '';}}
function profileKey(href){try{var u=new URL(String(href||''),location.href);if(!/(^|\.)facebook\.com$/i.test(u.hostname))return '';if(/\/profile\.php$/i.test(u.pathname)){var id=u.searchParams.get('id');return id?'id:'+id:'';}var first=decodeURIComponent((u.pathname.split('/').filter(Boolean)[0]||''));if(!first||RESERVED[first.toLowerCase()])return '';return first;}catch(_){return '';}}
function canonical(key,href){if(/^id:\d+$/.test(key))return 'https://www.facebook.com/profile.php?id='+key.slice(3);try{var u=new URL(href,location.href);return u.origin+'/'+encodeURIComponent(key);}catch(_){return 'https://www.facebook.com/'+encodeURIComponent(key);}}
function fixedOrSticky(el){var cur=el;for(var i=0;i<8&&cur&&cur!==document.body;i++,cur=cur.parentElement){try{var pos=String(getComputedStyle(cur).position||'').toLowerCase();if(pos==='fixed'||pos==='sticky')return true;}catch(_){ }}return false;}
function anchorGeometryInCorridor(a,startY,boundaryY){if(fixedOrSticky(a))return false;var y=docTop(a),b=docBottom(a);return b>=startY-20&&y<(boundaryY||Infinity)-8;}
function profileAnchors(startY,boundaryY){var all=document.querySelectorAll('a[href]'),out=[],target=targetKey();for(var i=0;i<all.length;i++){var a=all[i];if(toolNode(a)||!anchorGeometryInCorridor(a,startY,boundaryY))continue;var key=profileKey(hrefOf(a));if(!key||String(key).toLowerCase()===String(target).toLowerCase())continue;out.push({element:a,key:key,href:hrefOf(a),text:clean(a.innerText||a.textContent||a.getAttribute('aria-label')||'')});}return out;}
function commonAncestor(a,b){if(!a||!b)return null;var seen=[],x=a;for(var i=0;i<16&&x;i++,x=x.parentElement)seen.push(x);x=b;for(var j=0;j<16&&x;j++,x=x.parentElement){if(seen.indexOf(x)>=0)return x;}return null;}
function nearestCard(anchor,startY,boundaryY,peer){var cur=commonAncestor(anchor,peer)||anchor.parentElement||anchor,best=cur;for(var d=0;d<7&&cur&&cur!==document.body;d++,cur=cur.parentElement){var r=cur.getBoundingClientRect(),txt=clean(cur.innerText||cur.textContent||''),imgs=cur.querySelectorAll?cur.querySelectorAll('img[src]'):[];if(r.height>=48&&r.height<=620&&r.width>=140&&txt.length>0&&txt.length<1400){best=cur;if(imgs.length&&r.height>=70)return cur;}}return best||anchor.parentElement||anchor;}
function bestImage(card){var imgs=card&&card.querySelectorAll?card.querySelectorAll('img[src]'):[],best=null,score=-1;for(var i=0;i<imgs.length;i++){var im=imgs[i];if(toolNode(im))continue;var r=im.getBoundingClientRect(),w=Number(im.naturalWidth||im.width||im.getAttribute('width')||r.width||0),h=Number(im.naturalHeight||im.height||im.getAttribute('height')||r.height||0),s=Math.max(w,h)+(r.width>=40&&r.height>=40?500:0);if(s>score){score=s;best={url:String(im.currentSrc||im.src||''),width:w,height:h,alt:clean(im.alt||'')};}}return best||{url:'',width:0,height:0,alt:''};}
function nameFor(key,anchors,card,imgAlt){var best='';for(var i=0;i<anchors.length;i++){var t=clean(anchors[i].text);if(t&&t.length>best.length&&t.length<180)best=t;}if(!best&&imgAlt&&!/profile picture|foto do perfil/i.test(imgAlt))best=imgAlt;if(!best){var txt=clean(card&&card.innerText||'').split(/\n+/)[0];if(txt.length<180)best=txt;}return best||key.replace(/^id:/,'ID ');}
function imageClass(w,h){var m=Math.max(Number(w||0),Number(h||0));if(m>=960)return {c:'HD_REAL_960_PLUS',q:'HD 960+ estrito'};if(m>=640)return {c:'HD_REAL_640_PLUS',q:'HD 640+'};if(m>=300)return {c:'BEST_300_PLUS',q:'300+'};return {c:m?'THUMB_SMALL':'SEM_FOTO',q:m?'miniatura':'sem foto'};}
function relationRow(entry,relation){var d=imageClass(entry.image.width,entry.image.height),now=new Date().toISOString(),url=canonical(entry.key,entry.href);return {key:entry.key,relacao:REL_LABEL[relation]||relation,relation:relation,relationMemberships:[relation],username:entry.key,displayName:entry.name,nome:entry.name,profileUrl:url,perfil:url,avatarUrl:entry.image.url,fotoUrl:entry.image.url,fotoUrlHD:entry.image.url,avatarWidth:entry.image.width,avatarHeight:entry.image.height,fotoWidth:entry.image.width,fotoHeight:entry.image.height,imageClass:d.c,fotoClasse:d.c,imageEvidence:entry.image.url?'exact_relation_corridor_dom':'',fotoOrigem:entry.image.url?'exact_relation_corridor_dom':'',fotoBestSource:entry.image.url?'exact_relation_corridor_dom':'',fotoCandidatesTested:entry.image.url?1:0,qualidadeFoto:d.q,dimensaoFotoBaixada:entry.image.width&&entry.image.height?entry.image.width+'x'+entry.image.height:'',fonteFotoBaixada:entry.image.url?'exact_relation_corridor_dom':'',statusFoto:entry.image.url?'validada':'sem_foto',bio:'',bioText:'',linkExterno:'',externalUrl:'',seguidores:'',seguindo:'',curtidas:'',videos:'',postagens:'',amigos:'',privada:'',categoria:'',trabalho:'',localizacao:'',formacao:'',metadadosCompletos:'',detalhesRenderizados:[],statusMeta:'pending',profileMetaStatus:'pending',visualContext:entry.text.slice(0,600),metaConfidence:0,metaAudit:'vínculo coletado exclusivamente no corredor semântico de '+(REL_LABEL[relation]||relation),metaSources:['exact_relation_corridor_442127'],relationBinding:{requested:relation,materialized:relation,mode:'exact_selected_relation_corridor',release:RELEASE},seedSource:'exact_relation_corridor_442127',firstSeenAt:now,lastSeenAt:now};}
function mergeRow(old,row){for(var k in row){if(!Object.prototype.hasOwnProperty.call(row,k))continue;if(old[k]==null||old[k]===''||(Array.isArray(old[k])&&!old[k].length))old[k]=row[k];}old.lastSeenAt=row.lastSeenAt;old.relation=row.relation;old.relacao=row.relacao;old.relationMemberships=[row.relation];old.relationBinding=row.relationBinding;old.seedSource=row.seedSource;return old;}
function corridor(){var selected=selectedRelationControl(),head=relationHeading();if(!selected)return {ok:false,reason:'selected_relation_not_materialized'};var start=Math.max(docBottom(selected.element),head?docBottom(head):0),boundary=nextBoundary(start),sc=document.scrollingElement||document.documentElement,top=Number(window.scrollY||sc.scrollTop||0),vh=Math.max(1,Number(window.innerHeight||sc.clientHeight||1)),height=Math.max(vh,Number(sc.scrollHeight||vh)),physicalMax=Math.max(0,height-vh),safeMax=physicalMax;if(boundary)safeMax=Math.max(top,Math.min(physicalMax,boundary.top-vh+Math.max(80,Math.floor(vh*0.12))));var distance=Math.max(0,safeMax-top),endTolerance=boundary?Math.max(30,Math.floor(vh*0.30)):Math.max(18,Math.floor(vh*0.04));return {ok:true,relation:selected.relation,selected:selected,heading:head,startY:start,boundary:boundary,boundaryY:boundary?boundary.top:Infinity,top:top,viewport:vh,scrollHeight:height,physicalMax:physicalMax,safeMax:safeMax,distance:distance,atEnd:distance<=endTolerance,endTolerance:endTolerance};}
function scan(state,relation,audit){var c=corridor();if(!c.ok||c.relation!==relation)return {added:0,total:state.rows.size,corridor:c};var as=profileAnchors(c.startY,c.boundaryY),group={},i;for(i=0;i<as.length;i++){var kl=String(as[i].key).toLowerCase();if(!group[kl])group[kl]={key:as[i].key,href:as[i].href,anchors:[]};group[kl].anchors.push(as[i]);}
  var added=0,seen=0;for(var g in group){if(!Object.prototype.hasOwnProperty.call(group,g))continue;var x=group[g],hasImage=false;for(var hi=0;hi<x.anchors.length;hi++){try{if(x.anchors[hi].element.querySelector('img[src]')){hasImage=true;break;}}catch(_){ }}if(x.anchors.length<2&&!hasImage)continue;var img={url:'',width:0,height:0,alt:''},textNode=null;for(var gi=0;gi<x.anchors.length;gi++){var ga=x.anchors[gi].element,gt=clean(x.anchors[gi].text);if(gt&&!textNode)textNode=ga;try{var gim=ga.querySelector('img[src]');if(gim){var gr=gim.getBoundingClientRect();img={url:String(gim.currentSrc||gim.src||''),width:Number(gim.naturalWidth||gim.width||gim.getAttribute('width')||gr.width||0),height:Number(gim.naturalHeight||gim.height||gim.getAttribute('height')||gr.height||0),alt:clean(gim.alt||'')};}}catch(_){ }}var card=(textNode&&textNode.parentElement)||x.anchors[0].element.parentElement||x.anchors[0].element,name=nameFor(x.key,x.anchors,card,img.alt),row=relationRow({key:x.key,href:x.href,image:img,name:name,text:clean(card&&card.innerText||'')},relation);seen++;if(state.rows.has(x.key)){mergeRow(state.rows.get(x.key),row);if(state.stats){state.stats.rowsUpdated=(state.stats.rowsUpdated||0)+1;state.stats.duplicates=(state.stats.duplicates||0)+1;}}else{state.rows.set(x.key,row);added++;if(state.stats)state.stats.rowsInserted=(state.stats.rowsInserted||0)+1;}}
  if(state.stats){state.stats.domScans=(state.stats.domScans||0)+1;state.stats.domRowsSeen=(state.stats.domRowsSeen||0)+seen;}audit.lastScanAt=new Date().toISOString();audit.verifiedRows=state.rows.size;audit.rootProfileCount=Math.max(audit.rootProfileCount||0,state.rows.size);return {added:added,total:state.rows.size,corridor:c};}
function waitFrameAndMutation(ms){return new Promise(function(resolve){var done=false,obs=null,timer=null;function finish(){if(done)return;done=true;if(obs)obs.disconnect();if(timer)clearTimeout(timer);requestAnimationFrame(function(){requestAnimationFrame(resolve);});}try{obs=new MutationObserver(function(){setTimeout(finish,90);});obs.observe(document.body||document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['style','aria-busy']});}catch(_){ }timer=setTimeout(finish,ms||700);});}
function scrollToY(y){var sc=document.scrollingElement||document.documentElement,before=Number(window.scrollY||sc.scrollTop||0);try{window.scrollTo(0,Math.max(0,Math.floor(y)));}catch(_){try{sc.scrollTop=Math.max(0,Math.floor(y));}catch(__){ }}return before;}
function auditBase(relation){return {schema:'b35a1_exact_relation_corridor_442127',release:RELEASE,status:'running',requestedRelation:relation,materializedRelation:'',startedAt:new Date().toISOString(),completedAt:'',closureReason:'',verifiedRows:0,rootProfileCount:0,scrollRounds:0,requestedScrollMoves:0,actualScrollMoves:0,mutationWaits:0,boundaryConfirmations:0,physicalBottomConfirmations:0,stuckRounds:0,noGainRounds:0,bodyScrollStart:Number(window.scrollY||0),bodyScrollEnd:Number(window.scrollY||0),bodyScrollDelta:0,scrollTravelPx:0,initialRewindRequested:false,initialRewindObserved:false,initialRewindFrom:Number(window.scrollY||0),initialRewindTo:Number(window.scrollY||0),nextSectionLabel:'',nextSectionTop:0,lastSafeMax:0,lastScrollTop:0,lastScrollHeight:0,hardDeadlineReached:false,maxRoundsReached:false,noRefresh:true,noRouteNavigation:true,noAutomaticControlClick:true,noFriendsAll:true,noAlphabeticalSearch:true,noGenericSectionScan:true,noScrollIntoViewFallback:true,partial:false,errors:[]};}
function setRunningState(st,relation){st.stopRequested=false;st.stopReason='';st.stopAt='';st.runningScroll=true;st.runningMeta=false;st.relation=relation;st.expected=0;st.expectedHint=0;st.declaredRelationTarget=0;st.observedRelationCount=0;st.closedRelationCount=0;st.relationObservedClosed=false;st.relationTargetReached=false;st.relationVisibilityGap=false;st.relationSurfaceBlocked=false;st.bottomConfirmed=false;st.closureReason='';st.metaLimit=0;st.relationRunContext={locked:false,active:true,relation:relation,target:0,rawTarget:0,targetConfirmed:false,source:'exact_selected_relation_corridor_442127',confidence:500,startedAt:new Date().toISOString(),completedAt:''};}
function finishState(st,relation,audit,reason,complete){st.runningScroll=false;st.relation=relation;st.observedRelationCount=st.rows.size;st.closedRelationCount=st.rows.size;st.relationObservedClosed=true;st.relationTargetReached=false;st.bottomConfirmed=complete===true;st.closureReason=reason;st.expected=0;st.expectedHint=0;st.declaredRelationTarget=0;st.metaLimit=st.rows.size;st.expectedSource='exact_selected_relation_corridor_442127';st.relationVisibilityGap=false;st.relationSurfaceBlocked=false;if(st.relationRunContext){st.relationRunContext.active=false;st.relationRunContext.completedAt=new Date().toISOString();}audit.status=complete?'completed':'partial_completed';audit.partial=complete!==true;audit.closureReason=reason;audit.completedAt=new Date().toISOString();audit.bodyScrollEnd=Number(window.scrollY||0);audit.bodyScrollDelta=audit.bodyScrollEnd-audit.bodyScrollStart;audit.verifiedRows=st.rows.size;st.exactRelationAudit442127=audit;}
function pruneToKeys(st,keys){var remove=[];st.rows.forEach(function(_,k){if(!keys[String(k).toLowerCase()])remove.push(k);});for(var i=0;i<remove.length;i++)st.rows.delete(remove[i]);}
async function runExactRelation(relation,options){
  relation=/^(friends|following|followers)$/.test(String(relation||''))?String(relation):'';options=options||{};var core=window[CORE_NAME];if(!core||!core.state)throw new Error('B35_CORE_UNAVAILABLE_442127');var st=core.state,initial=corridor(),audit=auditBase(relation||initial.relation||'');
  if(!initial.ok){st.rows.clear();finishState(st,relation||'friends',audit,'selected_relation_not_materialized',true);audit.unavailable=true;return {relation:relation||'friends',total:0,unavailable:true,audit:audit};}
  if(!relation)relation=initial.relation;audit.requestedRelation=relation;audit.materializedRelation=initial.relation;
  if(initial.relation!==relation){st.rows.clear();finishState(st,relation,audit,'requested_'+relation+'_but_materialized_'+initial.relation,true);audit.unavailable=true;audit.relationMismatch=true;return {relation:relation,materializedRelation:initial.relation,total:0,unavailable:true,audit:audit};}
  st.rows.clear();setRunningState(st,relation);st.exactRelationAudit442127=audit;var rewindTarget=Math.max(0,Math.floor(initial.startY-Math.min(220,Math.max(100,initial.viewport*0.22))));if(initial.top>rewindTarget+8){audit.initialRewindRequested=true;audit.requestedScrollMoves++;var rewindBefore=initial.top;scrollToY(rewindTarget);audit.mutationWaits++;await waitFrameAndMutation(520);var rewound=corridor();if(rewound.ok){audit.initialRewindTo=rewound.top;audit.scrollTravelPx+=Math.abs(rewound.top-rewindBefore);if(Math.abs(rewound.top-rewindBefore)>2){audit.initialRewindObserved=true;audit.actualScrollMoves++;}}}var deadline=Date.now()+Math.max(30000,Number(options.maxMs||60000)),maxRounds=Math.max(20,Number(options.maxRounds||100)),lastCount=-1,lastHeight=-1,noGain=0,boundaryStable=0,bottomStable=0,boundarySince=0,bottomSince=0,stuck=0,complete=false,reason='';
  try{
    for(var round=0;round<maxRounds;round++){
      if(st.stopRequested){reason='stopped_by_user_partial';break;}
      if(Date.now()>=deadline){audit.hardDeadlineReached=true;reason='hard_deadline_partial_snapshot';break;}
      audit.scrollRounds=round+1;var before=scan(st,relation,audit),c=before.corridor;if(!c.ok||c.relation!==relation){reason='selected_relation_surface_lost_partial';break;}
      audit.nextSectionLabel=c.boundary?c.boundary.label:'';audit.nextSectionTop=c.boundary?c.boundary.top:0;audit.lastSafeMax=c.safeMax;audit.lastScrollTop=c.top;audit.lastScrollHeight=c.scrollHeight;
      var count=st.rows.size,height=c.scrollHeight,gain=count>lastCount,heightGain=height>lastHeight+8;if(gain||heightGain){noGain=0;}else noGain++;audit.noGainRounds=noGain;
      if(c.boundary&&c.atEnd&&!gain&&!heightGain){if(!boundarySince)boundarySince=Date.now();boundaryStable++;audit.boundaryConfirmations=boundaryStable;}else if(!c.atEnd||gain||heightGain){boundaryStable=0;boundarySince=0;}
      if(!c.boundary&&c.atEnd&&!gain&&!heightGain){if(!bottomSince)bottomSince=Date.now();bottomStable++;audit.physicalBottomConfirmations=bottomStable;}else if(!c.atEnd||gain||heightGain){bottomStable=0;bottomSince=0;}
      if(c.boundary&&boundaryStable>=3&&boundarySince&&Date.now()-boundarySince>=1500){complete=true;reason='explicit_next_section_boundary_stable';break;}
      if(!c.boundary&&bottomStable>=4&&bottomSince&&Date.now()-bottomSince>=2100){complete=true;reason='physical_bottom_stable';break;}
      var desired=c.boundary?c.safeMax:Math.min(c.safeMax,c.top+Math.max(420,Math.floor(c.viewport*1.22))),requested=desired>c.top+2,beforeTop=c.top;if(requested){audit.requestedScrollMoves++;scrollToY(desired);}else if(!c.atEnd){audit.requestedScrollMoves++;scrollToY(c.top+Math.max(300,Math.floor(c.viewport*0.65)));}
      audit.mutationWaits++;await waitFrameAndMutation(520);var after=corridor(),moved=after.ok?Math.abs(after.top-beforeTop)>2:false;if(moved){audit.actualScrollMoves++;audit.scrollTravelPx+=Math.abs(after.top-beforeTop);stuck=0;}else if(c.atEnd){stuck=0;}else{stuck++;audit.stuckRounds=stuck;if(stuck<=2){var nudge=Math.min(c.safeMax,c.top+Math.max(260,Math.floor(c.viewport*0.55)));audit.requestedScrollMoves++;scrollToY(nudge);audit.mutationWaits++;await waitFrameAndMutation(480);var retry=corridor();if(retry.ok&&Math.abs(retry.top-beforeTop)>2){audit.actualScrollMoves++;audit.scrollTravelPx+=Math.abs(retry.top-beforeTop);stuck=0;}}}
      if(stuck>=3&&!c.atEnd){reason='scroll_motion_unavailable_partial';break;}
      lastCount=count;lastHeight=height;
    }
    if(!reason){audit.maxRoundsReached=true;reason='max_rounds_partial_snapshot';}
    scan(st,relation,audit);var exact={};st.rows.forEach(function(_,k){exact[String(k).toLowerCase()]=1;});finishState(st,relation,audit,reason,complete);
    if(options.enrich!==false&&st.rows.size>0&&typeof core.fastEnrichStrict==='function'){
      try{st.stopRequested=false;await core.fastEnrichStrict();}catch(e){audit.errors.push('metadata:'+clean(e&&e.message||e));}finally{pruneToKeys(st,exact);st.runningMeta=false;st.stopRequested=false;st.stopReason='';st.stopAt='';finishState(st,relation,audit,reason,complete);}
    }
    return {relation:relation,materializedRelation:relation,total:st.rows.size,unavailable:false,complete:complete,closureReason:reason,audit:audit};
  }catch(e){audit.errors.push(clean(e&&e.message||e));finishState(st,relation,audit,'collector_exception_partial',false);throw e;}
}
function snapshotRelation(relation){var core=window[CORE_NAME],st=core&&core.state,rows=[];if(st&&st.rows)st.rows.forEach(function(r){rows.push(JSON.parse(JSON.stringify(r)));});return {schema:'b35a1_relation_snapshot_442127',release:RELEASE,relation:relation||st&&st.relation||'',rows:rows,audit:st&&st.exactRelationAudit442127?JSON.parse(JSON.stringify(st.exactRelationAudit442127)):null,unavailable:rows.length===0,createdAt:new Date().toISOString()};}
function unavailableSnapshot(relation,materialized,reason){return {schema:'b35a1_relation_snapshot_442127',release:RELEASE,relation:relation,materializedRelation:materialized||'',rows:[],unavailable:true,closureReason:reason||'relation_not_materialized_current_document',createdAt:new Date().toISOString()};}
function restoreRelationSuite(results){var core=window[CORE_NAME],st=core&&core.state;if(!st)return null;st.rows.clear();var membership={},order=['friends','following','followers'];for(var i=0;i<order.length;i++){var rel=order[i],snap=results&&results[rel],rows=snap&&snap.rows||[];for(var j=0;j<rows.length;j++){var r=JSON.parse(JSON.stringify(rows[j])),k=String(r.key||r.username||r.profileUrl||'');if(!k)continue;var kl=k.toLowerCase();if(!membership[kl])membership[kl]={row:r,rels:[]};if(membership[kl].rels.indexOf(rel)<0)membership[kl].rels.push(rel);}}
  Object.keys(membership).forEach(function(k){var x=membership[k],r=x.row;r.relationMemberships=x.rels.slice();r.relation=x.rels.join('|');r.relacao=x.rels.map(function(z){return REL_LABEL[z]||z;}).join(' | ');st.rows.set(r.key||r.username||k,r);});st.relation='all';st.observedRelationCount=st.rows.size;st.closedRelationCount=st.rows.size;st.relationObservedClosed=true;st.bottomConfirmed=true;st.expected=0;st.expectedHint=0;st.declaredRelationTarget=0;st.metaLimit=st.rows.size;st.expectedSource='exact_relation_suite_442127';st.closureReason='exact_relation_suite_current_document_completed';st.relationSuite442127=JSON.parse(JSON.stringify(results||{}));return relationSuiteSummary(results);}
function relationSuiteSummary(results){var core=window[CORE_NAME],st=core&&core.state,src=results||st&&st.relationSuite442127||{},counts={friends:0,following:0,followers:0},unavailable=[];['friends','following','followers'].forEach(function(r){var s=src[r];counts[r]=s&&s.rows?s.rows.length:0;if(!s||s.unavailable)unavailable.push(r);});var overlap=0;if(st&&st.rows)st.rows.forEach(function(r){if((r.relationMemberships||[]).length>1)overlap++;});return {active:true,release:RELEASE,counts:counts,uniqueProfiles:st&&st.rows?st.rows.size:0,overlapProfiles:overlap,unavailable:unavailable};}
function detect(){var c=corridor();return {ok:c.ok,relation:c.relation||'',selectedLabel:c.selected&&c.selected.label||'',startY:c.startY||0,boundaryLabel:c.boundary&&c.boundary.label||'',boundaryTop:c.boundary&&c.boundary.top||0,scrollTop:c.top||0,safeMax:c.safeMax||0};}

function slug(v){var s=clean(v).toLowerCase();try{s=s.normalize('NFD').replace(/[\u0300-\u036f]/g,'');}catch(_){ }return s.replace(/[^a-z0-9._-]+/g,'_').replace(/^_+|_+$/g,'')||'perfil';}
function stamp(){return new Date().toISOString().replace(/[:.]/g,'-');}
function exportBase(core){var st=core&&core.state||{},target=String(st.pageTargetKey||targetKey()||'perfil').replace(/^id:/,'id_');return 'fb_relacoes_b35a1_'+slug(target)+'_'+stamp();}
function bytesOf(data){if(data instanceof Uint8Array)return data;if(data instanceof ArrayBuffer)return new Uint8Array(data);if(data&&data.buffer instanceof ArrayBuffer)return new Uint8Array(data.buffer,data.byteOffset||0,data.byteLength||data.length||0);return new TextEncoder().encode(String(data==null?'':data));}
async function hashHex(alg,data){var b=bytesOf(data),h=await crypto.subtle.digest(alg,b),a=new Uint8Array(h),s='';for(var i=0;i<a.length;i++)s+=a[i].toString(16).padStart(2,'0');return s;}
function downloadData(name,data,mime){var blob=data instanceof Blob?data:new Blob([data],{type:mime||'application/octet-stream'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';(document.body||document.documentElement).appendChild(a);a.click();setTimeout(function(){try{a.remove();URL.revokeObjectURL(url);}catch(_){}},30000);}
function auditedSnapshot(core){var snap=core.freezeExportSnapshot?core.freezeExportSnapshot():{json:core.makeJson(),html:''};var st=core.state||{},audit=st.exactRelationAudit442127||null,suite=relationSuiteSummary(st.relationSuite442127||{});if(audit)snap.json.exactRelationAudit442127=JSON.parse(JSON.stringify(audit));if(st.relationSuite442127)snap.json.relationSuite442127={release:RELEASE,summary:suite,results:JSON.parse(JSON.stringify(st.relationSuite442127))};snap.json.releaseCandidate=RELEASE;snap.json.relation=snap.json.relation||{};snap.json.relation.exactCollectorRelease=RELEASE;snap.json.relation.semanticSubstitution=false;snap.json.relation.noRefresh=true;snap.json.totals=snap.json.totals||{};snap.json.totals.rows=st.rows?st.rows.size:0;snap.json.totals.observedRelationCount=st.rows?st.rows.size:0;snap.json.totals.closedRelationCount=st.rows?st.rows.size:0;snap.json.totals.bottomConfirmed=st.bottomConfirmed===true;snap.html=core.makeHtml?core.makeHtml(snap.json):snap.html;return snap;}
async function exactExportSelectedFormats(core,kinds,options){options=options||{};var selected=[],allowed={json:1,html:1,pdf:1,csv:1,xlsx:1};for(var i=0;i<(kinds||[]).length;i++){var k=String(kinds[i]||'').toLowerCase();if(allowed[k]&&selected.indexOf(k)<0)selected.push(k);}if(!selected.length)throw new Error('SELECIONE_AO_MENOS_UM_FORMATO');var printWindow=null;if(selected.indexOf('pdf')>=0){try{printWindow=window.open('about:blank','_blank');}catch(_){printWindow=null;}}var snapshot=auditedSnapshot(core),base=exportBase(core),out=[];for(var j=0;j<selected.length;j++){var kind=selected[j],artifact=core.buildExportArtifact(kind,base,snapshot),sha256=await hashHex('SHA-256',artifact.data),sha512=await hashHex('SHA-512',artifact.data);if(artifact.nativePrint===true){if(core.openHtmlReportNativePdf)core.openHtmlReportNativePdf(artifact.data,printWindow);else if(printWindow){printWindow.document.open();printWindow.document.write(artifact.data);printWindow.document.close();printWindow.focus();printWindow.print();}var source={kind:'html',name:artifact.sourceHtmlName||base+'.html',mime:'text/html;charset=utf-8',data:artifact.data},laudoPdf=core.makeIntegrityPdf(source,sha256,sha512),laudoPdfName=base+'_fonte_html_laudo_integridade.pdf';downloadData(laudoPdfName,laudoPdf,'application/pdf');out.push({name:artifact.name,mime:'application/pdf',mode:'native_print_exact_snapshot_442127',sourceHtmlSha256:sha256,sourceHtmlSha512:sha512,integrityPdf:laudoPdfName});}else{downloadData(artifact.name,artifact.data,artifact.mime);var laudo=core.makeIntegrityPdf(artifact,sha256,sha512),laudoName=artifact.name.replace(/\.[^.]+$/,'')+'_laudo_integridade.pdf';downloadData(laudoName,laudo,'application/pdf');out.push({name:artifact.name,mime:artifact.mime,sha256:sha256,sha512:sha512,integrityPdf:laudoName});}await new Promise(function(resolve){setTimeout(resolve,160);});}return out;}

function install(){var core=window[CORE_NAME];if(!core||!core.state)return false;core.detectExactMaterializedRelation=detect;core.runExactRelation=runExactRelation;core.snapshotRelation=snapshotRelation;core.makeUnavailableRelationSnapshot=unavailableSnapshot;core.restoreRelationSuite=restoreRelationSuite;core.relationSuiteSummary=relationSuiteSummary;core.autoScrollCollectAndEnrich=function(){var d=detect();return runExactRelation(d.relation||'friends',{enrich:true});};if(!core.__exactExport442127Installed){core.__stableExportSelectedFormats442127=core.exportSelectedFormats;core.exportSelectedFormats=function(kinds,options){return exactExportSelectedFormats(core,kinds,options);};core.__exactExport442127Installed=true;}core.relationProgressSnapshot=function(){var st=core.state,total=st.rows?st.rows.size:0,enriched=0;if(st.rows)st.rows.forEach(function(r){if(r&&r.statusMeta&&r.statusMeta!=='pending')enriched++;});var a=st.exactRelationAudit442127||{},pct=st.runningScroll?Math.min(99,Math.max(1,Number(a.actualScrollMoves||0)*4)):100;return {relation:st.relation,collected:total,enriched:enriched,target:0,targetConfirmed:false,listPct:pct,metaPct:total?enriched/total*100:0};};return true;}
var tries=0,timer=setInterval(function(){tries++;if(install()||tries>100)clearInterval(timer);},50);install();
window[NAME]={release:RELEASE,detect:detect,corridor:corridor,runExactRelation:runExactRelation,snapshotRelation:snapshotRelation,unavailableSnapshot:unavailableSnapshot,restoreRelationSuite:restoreRelationSuite,relationSuiteSummary:relationSuiteSummary,install:install};
})();
