/*
 * FB_B35A1 V44R21R18 — observador e continuador GraphQL de comentários de POST.
 * Executa no mundo MAIN. Conserva internamente o molde da requisição para
 * continuar a paginação, mas expõe ao mundo isolado somente comentários
 * sanitizados, cursores resumidos e contadores de auditoria. Nunca exporta
 * cookies, tokens, cabeçalhos, corpos de requisição ou respostas brutas.
 */
(function(){
  'use strict';
  if(window.__FB_POST_COMMENT_MAIN_V44R21R18__)return;
  var CHANNEL='FB_B35_POST_COMMENT_MAIN_V44R21R18';
  var CONTROL='FB_B35_POST_COMMENT_CONTROL_V44R21R18';
  var originalFetch=typeof window.fetch==='function'?window.fetch.bind(window):null;
  var XHR=window.XMLHttpRequest||null;
  var originalOpen=XHR&&XHR.prototype&&XHR.prototype.open;
  var originalSend=XHR&&XHR.prototype&&XHR.prototype.send;
  var state={routeKey:'',armed:false,declaredTarget:0,comments:{},templates:{},templateOrder:[],graphqlResponses:0,commentResponses:0,replayRequests:0,replaySuccess:0,replayErrors:0,rejectedResponses:0,updatedAt:'',installedAt:new Date().toISOString(),seq:0};
  function text(v){return String(v==null?'':v).replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/\s+/g,' ').trim();}
  function routeKey(){var s=String(location.href||''),m=s.match(/\/posts\/(pfbid[\w-]+)/i);if(m&&m[1])return m[1];m=s.match(/\/posts\/(\d+)/i);return m&&m[1]||'';}
  function isPostRoute(){return /\/posts\/(?:pfbid[\w-]+|\d+)/i.test(String(location.href||''));}
  function ensureRoute(){var k=routeKey();if(k!==state.routeKey){state.routeKey=k;state.comments={};state.templates={};state.templateOrder=[];state.graphqlResponses=0;state.commentResponses=0;state.replayRequests=0;state.replaySuccess=0;state.replayErrors=0;state.rejectedResponses=0;state.updatedAt=new Date().toISOString();}return k;}
  function post(type,payload){try{window.postMessage({channel:CHANNEL,type:type,at:new Date().toISOString(),payload:payload||{}},location.origin);}catch(_){}}
  function parsePieces(raw){var s=String(raw||'').replace(/^\s*for\s*\(;;\);\s*/,'').trim(),out=[];function add(x){x=String(x||'').replace(/^\s*for\s*\(;;\);\s*/,'').trim();if(!x)return;try{out.push(JSON.parse(x));}catch(_){}}add(s);if(!out.length)s.split(/\r?\n/).forEach(add);return out;}
  function bodyString(body){if(typeof body==='string')return body;try{if(body instanceof URLSearchParams)return body.toString();}catch(_){}return '';}
  function headersObject(h){var out={};try{if(!h)return out;if(typeof h.forEach==='function'){h.forEach(function(v,k){out[String(k)]=String(v);});return out;}if(Array.isArray(h)){h.forEach(function(x){if(x&&x.length>=2)out[String(x[0])]=String(x[1]);});return out;}Object.keys(h).forEach(function(k){out[String(k)]=String(h[k]);});}catch(_){}return out;}
  function requestMeta(body){var raw=bodyString(body),out={raw:raw,friendlyName:'',docId:'',variablesRaw:'',variables:null,commentRequest:false};try{var p=new URLSearchParams(raw);out.friendlyName=text(p.get('fb_api_req_friendly_name')||'');out.docId=text(p.get('doc_id')||'');out.variablesRaw=String(p.get('variables')||'');if(out.variablesRaw)out.variables=JSON.parse(out.variablesRaw);}catch(_){}var probe=(out.friendlyName+' '+out.variablesRaw).toLowerCase();out.commentRequest=/(?:ufi|comment|feedback).*(?:comment|display|provider)|(?:comment|display).*(?:ufi|feedback)/i.test(probe)&&!/reactor|reaction|liker|people.*react/i.test(probe);return out;}
  function templateId(meta,url,source){return String(source||'fetch')+'|'+String(meta.docId||meta.friendlyName||'unknown')+'|'+String(url||'').slice(0,180);}
  function registerTemplate(meta,url,method,headers,source){if(!meta||!meta.commentRequest||!meta.raw||!isPostRoute())return null;ensureRoute();var id=templateId(meta,url,source),old=state.templates[id]||{};state.templates[id]={id:id,url:String(url||'/api/graphql/'),method:String(method||'POST').toUpperCase(),headers:headersObject(headers),body:meta.raw,friendlyName:meta.friendlyName,docId:meta.docId,variablesRaw:meta.variablesRaw,hasNext:old.hasNext===true,endCursor:old.endCursor||'',lastCursor:old.lastCursor||'',inFlight:false,lastUsedAt:old.lastUsedAt||'',source:String(source||'fetch')};if(state.templateOrder.indexOf(id)<0)state.templateOrder.push(id);while(state.templateOrder.length>12){var drop=state.templateOrder.shift();delete state.templates[drop];}return state.templates[id];}
  function first(obj,keys){if(!obj||typeof obj!=='object')return '';for(var i=0;i<keys.length;i++){var v=obj[keys[i]];if(typeof v==='string'&&text(v))return text(v);}return '';}
  function urlValue(v){if(typeof v==='string'&&/^https?:\/\//i.test(v))return v;if(v&&typeof v==='object'){var u=first(v,['uri','url','src','base_url']);if(/^https?:\/\//i.test(u))return u;}return '';}
  function profileUrl(raw,id){try{var x=new URL(String(raw||''),location.href);if(!/(^|\.)facebook\.com$/i.test(x.hostname))throw 0;if(/\/profile\.php$/i.test(x.pathname)){var q=x.searchParams.get('id');return q?'https://www.facebook.com/profile.php?id='+encodeURIComponent(q):'';}var p=x.pathname.split('/').filter(Boolean)[0]||'';if(!p||/^(?:reel|reels|photo|photos|posts|videos|watch|groups|events|marketplace|profile)$/i.test(p))throw 0;return 'https://www.facebook.com/'+encodeURIComponent(p);}catch(_){return /^\d{5,}$/.test(String(id||''))?'https://www.facebook.com/profile.php?id='+encodeURIComponent(String(id)):'';}}
  function avatar(obj){if(!obj||typeof obj!=='object')return '';var keys=['profile_picture','profilePicture','profile_pic','profilePic','avatar','picture','image'];for(var i=0;i<keys.length;i++){var u=urlValue(obj[keys[i]]);if(u)return u;}return '';}
  function commentCandidate(obj,path,requestBound){if(!requestBound||!obj||typeof obj!=='object')return;var typ=text(obj.__typename||obj.typename||obj.type||''),id=first(obj,['id','legacy_fbid','legacyFbid','comment_id','commentId']);var authorObj=obj.author||obj.actor||obj.user||obj.commenter||null;var name=authorObj&&first(authorObj,['name','display_name','displayName','short_name','shortName'])||'';var body=obj.body||obj.message||obj.comment_body||obj.commentBody||null,content='';if(typeof body==='string')content=text(body);else if(body&&typeof body==='object')content=first(body,['text','message','body']);if(!content)content=first(obj,['text','message_text','messageText']);var attachment=obj.attachments||obj.attachment||null;var looks=/comment|ufi_comment/i.test(typ)||(/comment/i.test(path)&&!!authorObj&&(!!content||!!attachment));if(!looks||!name||(!content&&!attachment))return;var aid=authorObj&&first(authorObj,['id','profile_id','profileId','actor_id','actorId'])||'',purl=profileUrl(authorObj&&first(authorObj,['url','profile_url','profileUrl','uri'])||'',aid);if(!purl)return;var parent='';try{parent=first(obj,['parent_comment_id','parentCommentId']);if(!parent&&obj.parent_comment)parent=first(obj.parent_comment,['id','legacy_fbid']);if(!parent&&obj.parent)parent=first(obj.parent,['id','legacy_fbid']);}catch(_){}var created=obj.created_time||obj.createdTime||obj.timestamp||'',likes=0;try{likes=Number(obj.feedback&&obj.feedback.reactors&&obj.feedback.reactors.count||obj.reaction_count||obj.reactionCount||0);}catch(_){}var media=[];function scanAtt(v,depth){if(depth>5||v==null)return;if(Array.isArray(v)){for(var i=0;i<v.length;i++)scanAtt(v[i],depth+1);return;}if(typeof v!=='object')return;Object.keys(v).forEach(function(k){var val=v[k],u=urlValue(val);if(u&&/(?:fbcdn\.net|giphy|tenor)/i.test(u)&&/image|uri|url|src|sticker|media/i.test(k))media.push({url:u,type:/gif/i.test(u)?'gif':'image'});if(val&&typeof val==='object')scanAtt(val,depth+1);});}scanAtt(attachment,0);var key=id?('id:'+id):(purl+'|'+content+'|'+created),old=state.comments[key],item={sourceId:id||key,parentId:parent||'',author:name,authorHref:purl,avatarUrl:avatar(authorObj),text:content,likes:likes,date:created?String(created):'',dateISO:null,media:media.slice(0,8),sourcePath:path,bindingReason:'ARMED_POST_GRAPHQL_COMMENT_QUERY_V44R21R18'};if(!old)state.comments[key]=item;else{if(!old.text&&item.text)old.text=item.text;if(!old.avatarUrl&&item.avatarUrl)old.avatarUrl=item.avatarUrl;if(!old.parentId&&item.parentId)old.parentId=item.parentId;if(item.media.length>old.media.length)old.media=item.media;}}
  function pageInfoCandidate(obj,template){if(!obj||typeof obj!=='object')return;var has=obj.has_next_page;if(has==null)has=obj.hasNextPage;var cursor=obj.end_cursor;if(cursor==null)cursor=obj.endCursor;if(typeof has!=='boolean'&&cursor==null)return;if(template){template.hasNext=has===true;template.endCursor=cursor==null?'':String(cursor);}}
  function walk(value,ctx,path,depth){if(depth>38||value==null)return;if(Array.isArray(value)){for(var i=0;i<value.length;i++)walk(value[i],ctx,path+'['+i+']',depth+1);return;}if(typeof value!=='object')return;commentCandidate(value,path,ctx.requestBound);pageInfoCandidate(value,ctx.template);var keys=Object.keys(value);for(var j=0;j<keys.length;j++)walk(value[keys[j]],ctx,path+'.'+keys[j],depth+1);}
  function snapshot(){ensureRoute();var comments=Object.keys(state.comments).map(function(k){return state.comments[k];}).slice(0,5000),temps=state.templateOrder.map(function(id){var x=state.templates[id];return x?{friendlyName:x.friendlyName,docId:x.docId,hasNext:x.hasNext===true,endCursor:!!x.endCursor,inFlight:!!x.inFlight,lastUsedAt:x.lastUsedAt||'',source:x.source||''}:null;}).filter(Boolean);return {version:'POST_COMMENT_NETWORK_V44R21R18',routeKey:state.routeKey,armed:state.armed,declaredTarget:state.declaredTarget,comments:comments,hasNext:temps.some(function(x){return x.hasNext&&x.endCursor;}),audit:{graphqlResponses:state.graphqlResponses,commentResponses:state.commentResponses,commentCandidates:comments.length,templates:temps,replayRequests:state.replayRequests,replaySuccess:state.replaySuccess,replayErrors:state.replayErrors,rejectedResponses:state.rejectedResponses,updatedAt:state.updatedAt,installedAt:state.installedAt}};}
  function emit(reason){state.updatedAt=new Date().toISOString();post('POST_COMMENT_SNAPSHOT',{reason:reason||'update',snapshot:snapshot()});}
  function inspect(raw,meta,template){var roots=parsePieces(raw);if(!roots.length){state.rejectedResponses++;return;}state.graphqlResponses++;if(meta&&meta.commentRequest)state.commentResponses++;var before=Object.keys(state.comments).length;for(var i=0;i<roots.length;i++)walk(roots[i],{requestBound:!!(meta&&meta.commentRequest),template:template||null},'$['+i+']',0);if(state.armed&&(Object.keys(state.comments).length>before||(meta&&meta.commentRequest)))emit('graphql');}
  function updateCursorValue(value,cursor,depth,seen){if(depth>24||value==null)return false;var changed=false;if(Array.isArray(value)){for(var i=0;i<value.length;i++)if(updateCursorValue(value[i],cursor,depth+1,seen))changed=true;return changed;}if(typeof value!=='object')return false;if(seen.indexOf(value)>=0)return false;seen.push(value);Object.keys(value).forEach(function(k){var low=String(k).toLowerCase(),v=value[k];if(/^(?:after|cursor|aftercursor|commentsaftercursor|commentcursor|endcursor)$/.test(low)){value[k]=cursor;changed=true;}else if(v&&typeof v==='object'&&updateCursorValue(v,cursor,depth+1,seen))changed=true;});return changed;}
  function bodyWithCursor(template,cursor){try{var p=new URLSearchParams(String(template.body||'')),raw=String(p.get('variables')||''),vars=raw?JSON.parse(raw):{};var changed=updateCursorValue(vars,cursor,0,[]);if(!changed)vars.after=cursor;p.set('variables',JSON.stringify(vars));return p.toString();}catch(_){return '';}}
  function replayHeaders(template){var h={},src=template&&template.headers||{};Object.keys(src).forEach(function(k){var low=String(k).toLowerCase();if(low==='content-length'||low==='host'||low==='cookie'||low==='origin'||low==='referer')return;h[k]=src[k];});if(!Object.keys(h).some(function(k){return String(k).toLowerCase()==='content-type';}))h['content-type']='application/x-www-form-urlencoded';return h;}
  function requestNext(){ensureRoute();if(!state.armed||!originalFetch)return Promise.resolve(false);var chosen=null;for(var i=state.templateOrder.length-1;i>=0;i--){var x=state.templates[state.templateOrder[i]];if(x&&x.hasNext&&x.endCursor&&!x.inFlight&&x.lastCursor!==x.endCursor){chosen=x;break;}}if(!chosen)return Promise.resolve(false);var cursor=chosen.endCursor,newBody=bodyWithCursor(chosen,cursor);if(!newBody)return Promise.resolve(false);chosen.inFlight=true;chosen.lastCursor=cursor;chosen.lastUsedAt=new Date().toISOString();state.replayRequests++;return originalFetch(chosen.url,{method:chosen.method||'POST',credentials:'include',body:newBody,headers:replayHeaders(chosen)}).then(function(resp){if(!resp||!resp.clone)throw new Error('POST_COMMENT_REPLAY_NO_RESPONSE');return resp.clone().text().then(function(raw){chosen.inFlight=false;state.replaySuccess++;var meta=requestMeta(newBody);inspect(raw,meta,chosen);emit('replay_success');return true;});}).catch(function(){chosen.inFlight=false;state.replayErrors++;emit('replay_error');return false;});}
  function arm(detail){ensureRoute();state.armed=true;state.declaredTarget=Math.max(0,Number(detail&&detail.declaredTarget||0));emit('armed');}
  function reset(){state.armed=false;state.declaredTarget=0;state.comments={};state.templates={};state.templateOrder=[];emit('reset');}
  function installFetch(){if(!originalFetch)return;window.fetch=function(input,init){var url=typeof input==='string'?input:(input&&input.url)||'',body=init&&init.body||'',meta=requestMeta(body),template=null;if(/graphql/i.test(url)&&meta.commentRequest)template=registerTemplate(meta,url,init&&init.method||'POST',init&&init.headers||(input&&input.headers), 'fetch');return originalFetch(input,init).then(function(resp){try{if(/graphql/i.test(url)&&resp&&resp.clone){resp.clone().text().then(function(raw){if(raw&&raw.length<=32*1024*1024)inspect(raw,meta,template);}).catch(function(){});}}catch(_){}return resp;});};}
  function installXHR(){if(!XHR||!originalOpen||!originalSend)return;XHR.prototype.open=function(method,url){this.__fbPostCommentUrlV44R21R18=String(url||'');this.__fbPostCommentMethodV44R21R18=String(method||'POST');return originalOpen.apply(this,arguments);};XHR.prototype.send=function(body){var self=this,meta=requestMeta(body),template=null;if(/graphql/i.test(self.__fbPostCommentUrlV44R21R18||'')&&meta.commentRequest)template=registerTemplate(meta,self.__fbPostCommentUrlV44R21R18,self.__fbPostCommentMethodV44R21R18,{},'xhr');try{self.addEventListener('load',function(){try{if(!/graphql/i.test(self.__fbPostCommentUrlV44R21R18||'')||typeof self.responseText!=='string'||self.responseText.length>32*1024*1024)return;inspect(self.responseText,meta,template);}catch(_){}},{once:true});}catch(_){}return originalSend.apply(this,arguments);};}
  window.addEventListener('message',function(ev){if(ev.source!==window)return;var d=ev.data;if(!d||d.channel!==CONTROL)return;if(d.type==='ARM_POST_COMMENTS')arm(d.payload||{});else if(d.type==='GET_POST_COMMENTS')emit('request');else if(d.type==='REQUEST_POST_COMMENT_NEXT')requestNext();else if(d.type==='RESET_POST_COMMENTS')reset();});
  ensureRoute();installFetch();installXHR();
  var marker=Object.freeze({version:'V44R21R18',installed:true,trust:'HOST_CONTEXT_UNTRUSTED',apiExposed:false});
  window.__FB_POST_COMMENT_MAIN_V44R21R18__=marker;
  setTimeout(function(){emit('installed');},0);
})();
