/*
 * FB_B35A1 V44R21R15 — evidência sanitizada de REEL no mundo MAIN (binding estrito de mídia).
 * Observa respostas já recebidas pelo navegador e conserva apenas:
 * URL de mídia/poster vinculada ao Reel, comentários materializados pela rede
 * e metadados mínimos de auditoria. Não exporta cookies, tokens, headers,
 * corpos de requisição nem respostas brutas.
 */
(function(){
  'use strict';
  if(window.__FB_REEL_EVIDENCE_MAIN_V44R21R14__)return;
  var CHANNEL='FB_B35_REEL_EVIDENCE_MAIN_V44R21R14';
  var CONTROL='FB_B35_REEL_EVIDENCE_CONTROL_V44R21R14';
  var originalFetch=typeof window.fetch==='function'?window.fetch.bind(window):null;
  var XHR=window.XMLHttpRequest||null;
  var originalOpen=XHR&&XHR.prototype&&XHR.prototype.open;
  var originalSend=XHR&&XHR.prototype&&XHR.prototype.send;
  var state={reelId:'',media:{},posters:{},comments:{},graphqlResponses:0,relevantResponses:0,rejectedUnboundMedia:0,rejectedUnsafeMedia:0,acceptedRequestBoundMedia:0,rejectedUnboundPosters:0,updatedAt:'',installedAt:new Date().toISOString(),seq:0};
  function text(v){return String(v==null?'':v).replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/\s+/g,' ').trim();}
  function routeId(){var m=String(location.pathname||'').match(/\/reel\/(\d+)/i);return m&&m[1]||'';}
  function ensureRoute(){var id=routeId();if(id!==state.reelId){state.reelId=id;state.media={};state.posters={};state.comments={};state.graphqlResponses=0;state.relevantResponses=0;state.rejectedUnboundMedia=0;state.rejectedUnsafeMedia=0;state.acceptedRequestBoundMedia=0;state.rejectedUnboundPosters=0;state.updatedAt=new Date().toISOString();}return id;}
  function post(type,payload){try{window.postMessage({channel:CHANNEL,type:type,at:new Date().toISOString(),payload:payload||{}},location.origin);}catch(_){}}
  function parsePieces(raw){var s=String(raw||'').replace(/^\s*for\s*\(;;\);\s*/,'').trim(),out=[];function add(x){x=String(x||'').replace(/^\s*for\s*\(;;\);\s*/,'').trim();if(!x)return;try{out.push(JSON.parse(x));}catch(_){}}add(s);if(!out.length)s.split(/\r?\n/).forEach(add);return out;}
  function bodyString(body){if(typeof body==='string')return body;try{if(body instanceof URLSearchParams)return body.toString();}catch(_){}return '';}
  function requestMeta(body){var raw=bodyString(body),out={friendlyName:'',docId:'',variables:'',bound:false,commentRequest:false,videoRequest:false};try{var p=new URLSearchParams(raw);out.friendlyName=text(p.get('fb_api_req_friendly_name')||'');out.docId=text(p.get('doc_id')||'');out.variables=String(p.get('variables')||'');}catch(_){}var id=ensureRoute();out.bound=!!(id&&raw.indexOf(id)>=0);out.commentRequest=/comment|ufi|feedback/i.test(out.friendlyName+' '+out.variables);out.videoRequest=/video|reel|unifiedvideocontainer/i.test(out.friendlyName+' '+out.variables);return out;}
  function first(obj,keys){if(!obj||typeof obj!=='object')return '';for(var i=0;i<keys.length;i++){var v=obj[keys[i]];if(typeof v==='string'&&text(v))return text(v);}return '';}
  function urlValue(v){if(typeof v==='string'&&/^https?:\/\//i.test(v))return v;if(v&&typeof v==='object'){var u=first(v,['uri','url','src','base_url','playable_url']);if(/^https?:\/\//i.test(u))return u;}return '';}
  function nestedUrl(v,depth){var direct=urlValue(v);if(direct)return direct;if(depth<=0||!v||typeof v!=='object')return '';var pref=['image','preferred_image','preferred_thumbnail','thumbnail','poster','preview_image','video','media'];for(var i=0;i<pref.length;i++){if(v[pref[i]]!=null){var u=nestedUrl(v[pref[i]],depth-1);if(u)return u;}}var keys=Object.keys(v).slice(0,80);for(var j=0;j<keys.length;j++){var val=v[keys[j]];if(val&&typeof val==='object'){var x=nestedUrl(val,depth-1);if(x)return x;}}return '';}
  function profileUrl(raw,id){try{var x=new URL(String(raw||''),location.href);if(!/(^|\.)facebook\.com$/i.test(x.hostname))throw 0;if(/\/profile\.php$/i.test(x.pathname)){var q=x.searchParams.get('id');return q?'https://www.facebook.com/profile.php?id='+encodeURIComponent(q):'';}var p=x.pathname.split('/').filter(Boolean)[0]||'';if(!p||/^(?:reel|reels|photo|photos|posts|videos|watch|groups|events|marketplace|profile)$/i.test(p))throw 0;return 'https://www.facebook.com/'+encodeURIComponent(p);}catch(_){return /^\d{5,}$/.test(String(id||''))?'https://www.facebook.com/profile.php?id='+encodeURIComponent(String(id)):'';}}
  function avatar(obj){if(!obj||typeof obj!=='object')return '';var keys=['profile_picture','profilePicture','profile_pic','profilePic','avatar','picture','image'];for(var i=0;i<keys.length;i++){var u=urlValue(obj[keys[i]]);if(u)return u;}return '';}
  function objectHasTarget(obj,id){if(!obj||typeof obj!=='object'||!id)return false;var keys=['id','video_id','videoId','reel_id','reelId','story_fbid','storyFbid','legacy_fbid','legacyFbid','media_id','mediaId'];for(var i=0;i<keys.length;i++){var v=obj[keys[i]];if(v!=null&&String(v)===String(id))return true;}var urls=['url','uri','permalink_url','permalinkUrl','www_url','wwwUrl'];for(var j=0;j<urls.length;j++){var u=obj[urls[j]];if(typeof u==='string'&&(u.indexOf('/reel/'+id)>=0||u.indexOf('/reels/'+id)>=0))return true;}return false;}
  function addMedia(raw,key,path,bound,requestBound,videoRequest){
    var u=nestedUrl(raw,4),low=String(key||'').toLowerCase(),p=String(path||'').toLowerCase();
    if(!u)return;
    if(!/^https?:\/\//i.test(u)||/\.(?:jpe?g|png|webp|gif|svg)(?:[?#]|$)/i.test(u)||/\.(?:m3u8|mpd|m4s)(?:[?#]|$)/i.test(u)){state.rejectedUnsafeMedia++;return;}
    if(!/(?:fbcdn\.net|akamaihd\.net|\.mp4(?:[?#]|$)|video)/i.test(u)){state.rejectedUnsafeMedia++;return;}
    var highSignal=/^(?:playable_url(?:_quality_hd)?|browser_native_(?:hd|sd)_url|downloadable_url|progressive_url|video_url|hd_src|sd_src|source_url)$/i.test(String(key||''));
    var foreignPath=/(?:recommend|related|up_next|upnext|watch_next|suggest|sponsored|ad_break|next_video)/i.test(p);
    var exact=!!bound,requestExact=!exact&&!!requestBound&&!!videoRequest&&highSignal&&!foreignPath;
    if(!exact&&!requestExact){state.rejectedUnboundMedia++;return;}
    var score=exact?100000:76000;
    if(/quality_hd|native_hd|hd_url|hd_src/i.test(low))score+=9000;
    if(/playable_url/i.test(low))score+=5000;
    if(/native_sd|sd_url|sd_src/i.test(low))score+=2500;
    if(/download/i.test(low))score+=3500;
    if(/\.mp4(?:[?#]|$)/i.test(u))score+=5000;
    if(requestExact)state.acceptedRequestBoundMedia++;
    var k=u.split('#')[0],old=state.media[k],reason=exact?'GRAPHQL_OBJECT_CONTAINS_ACTIVE_REEL_ID':'GRAPHQL_VIDEO_REQUEST_CONTAINS_ACTIVE_REEL_ID';
    if(!old||score>old.score)state.media[k]={url:u,key:key,path:path,bound:true,routeId:state.reelId,bindingReason:reason,requestBound:requestExact,score:score};
  }
  function addPoster(raw,key,path,bound){var u=nestedUrl(raw,4);if(!u||!/(?:fbcdn\.net|\.jpe?g|\.png|\.webp)(?:[?#]|$)/i.test(u))return;if(!bound){state.rejectedUnboundPosters++;return;}var score=100000+(/preferred|poster/i.test(key)?5000:1000);var k=u.split('#')[0],old=state.posters[k];if(!old||score>old.score)state.posters[k]={url:u,key:key,path:path,bound:true,routeId:state.reelId,bindingReason:'GRAPHQL_OBJECT_CONTAINS_ACTIVE_REEL_ID',score:score};}
  function addDash(str,path,bound){var s=String(str||'').replace(/\\u0025/gi,'%').replace(/\\u0026/gi,'&').replace(/\\\//g,'/').replace(/&amp;/gi,'&');var re=/(https?:\/\/[^\s"'<>]+?)(?:<|\s|"|')/gi,m;while((m=re.exec(s))!==null){if(/fbcdn\.net/i.test(m[1]))addMedia(m[1],'dash_manifest',path,bound);}}
  function commentCandidate(obj,path,bound,requestBound){if(!obj||typeof obj!=='object')return;var typ=text(obj.__typename||obj.typename||obj.type||''),id=first(obj,['id','legacy_fbid','legacyFbid','comment_id','commentId']);var authorObj=obj.author||obj.actor||obj.user||obj.commenter||null;var name=authorObj&&first(authorObj,['name','display_name','displayName','short_name','shortName'])||'';var body=obj.body||obj.message||obj.comment_body||obj.commentBody||null;var content='';if(typeof body==='string')content=text(body);else if(body&&typeof body==='object')content=first(body,['text','message','body']);if(!content)content=first(obj,['text','message_text','messageText']);var attachment=obj.attachments||obj.attachment||null;var looks=/comment|ufi_comment/i.test(typ)||(/comment/i.test(path)&&!!authorObj&&(!!content||!!attachment));if(!looks||!name||(!content&&!attachment))return;if(!bound&&!requestBound)return;var aid=authorObj&&first(authorObj,['id','profile_id','profileId','actor_id','actorId'])||'',purl=profileUrl(authorObj&&first(authorObj,['url','profile_url','profileUrl','uri'])||'',aid);if(!purl)return;var parent='';try{parent=first(obj,['parent_comment_id','parentCommentId']);if(!parent&&obj.parent_comment)parent=first(obj.parent_comment,['id','legacy_fbid']);if(!parent&&obj.parent)parent=first(obj.parent,['id','legacy_fbid']);}catch(_){}var created=obj.created_time||obj.createdTime||obj.timestamp||'';var likes=0;try{likes=Number(obj.feedback&&obj.feedback.reactors&&obj.feedback.reactors.count||obj.reaction_count||obj.reactionCount||0);}catch(_){}var media=[];function scanAtt(v,depth){if(depth>5||v==null)return;if(Array.isArray(v)){for(var i=0;i<v.length;i++)scanAtt(v[i],depth+1);return;}if(typeof v!=='object')return;Object.keys(v).forEach(function(k){var val=v[k],u=urlValue(val);if(u&&/(?:fbcdn\.net|giphy|tenor)/i.test(u)&&/image|uri|url|src|sticker|media/i.test(k))media.push({url:u,type:/gif/i.test(u)?'gif':'image'});if(val&&typeof val==='object')scanAtt(val,depth+1);});}scanAtt(attachment,0);var key=id?('id:'+id):(purl+'|'+content+'|'+created);var old=state.comments[key],item={sourceId:id||key,parentId:parent||'',author:name,authorHref:purl,avatarUrl:avatar(authorObj),text:content,likes:likes,date:created?String(created):'',dateISO:null,media:media.slice(0,8),sourcePath:path,bound:!!bound};if(!old)state.comments[key]=item;else{if(!old.text&&item.text)old.text=item.text;if(!old.avatarUrl&&item.avatarUrl)old.avatarUrl=item.avatarUrl;if(!old.parentId&&item.parentId)old.parentId=item.parentId;if(item.media.length>old.media.length)old.media=item.media;}}
  function walk(value,ctx,path,depth){if(depth>34||value==null)return;if(Array.isArray(value)){for(var i=0;i<value.length;i++)walk(value[i],ctx,path+'['+i+']',depth+1);return;}if(typeof value!=='object')return;var id=ensureRoute(),localBound=ctx.bound||objectHasTarget(value,id);commentCandidate(value,path,localBound,ctx.requestBound);var keys=Object.keys(value);for(var j=0;j<keys.length;j++){var k=keys[j],v=value[k],low=k.toLowerCase();if(typeof v==='string'){if(/dash_manifest|manifest/.test(low))addDash(v,path+'.'+k,localBound);if(/playable|browser_native|downloadable|progressive|base_url|video_url|hd_src|sd_src|source_url/.test(low))addMedia(v,k,path+'.'+k,localBound,ctx.requestBound,ctx.videoRequest);if(/thumbnail|poster|preview_image|preferred_thumbnail/.test(low))addPoster(v,k,path+'.'+k,localBound);}else if(v&&typeof v==='object'){if(/playable|browser_native|downloadable|progressive|base_url|video_url|hd_src|sd_src/.test(low))addMedia(v,k,path+'.'+k,localBound,ctx.requestBound,ctx.videoRequest);if(/thumbnail|poster|preview_image|preferred_thumbnail/.test(low))addPoster(v,k,path+'.'+k,localBound);}walk(v,{bound:localBound,requestBound:ctx.requestBound,videoRequest:ctx.videoRequest},path+'.'+k,depth+1);}}
  function snapshot(){ensureRoute();var media=Object.keys(state.media).map(function(k){return state.media[k];}).filter(function(x){return x&&x.bound===true&&String(x.routeId||state.reelId)===String(state.reelId);}).sort(function(a,b){return b.score-a.score;}).slice(0,40),posters=Object.keys(state.posters).map(function(k){return state.posters[k];}).filter(function(x){return x&&x.bound===true&&String(x.routeId||state.reelId)===String(state.reelId);}).sort(function(a,b){return b.score-a.score;}).slice(0,40),comments=Object.keys(state.comments).map(function(k){return state.comments[k];}).slice(0,1200);return {version:'REEL_EVIDENCE_V44R21R28',reelId:state.reelId,media:media,posters:posters,comments:comments,audit:{graphqlResponses:state.graphqlResponses,relevantResponses:state.relevantResponses,mediaCandidates:media.length,posterCandidates:posters.length,rejectedUnboundMedia:state.rejectedUnboundMedia,rejectedUnsafeMedia:state.rejectedUnsafeMedia,acceptedRequestBoundMedia:state.acceptedRequestBoundMedia,rejectedUnboundPosters:state.rejectedUnboundPosters,commentCandidates:comments.length,updatedAt:state.updatedAt,installedAt:state.installedAt}};}
  function emitSnapshot(reason){state.updatedAt=new Date().toISOString();post('REEL_EVIDENCE_SNAPSHOT',{reason:reason||'update',snapshot:snapshot()});}
  function inspect(raw,meta){meta=meta||{};var roots=parsePieces(raw);if(!roots.length)return;state.graphqlResponses++;var before=Object.keys(state.media).length+Object.keys(state.posters).length+Object.keys(state.comments).length;for(var i=0;i<roots.length;i++)walk(roots[i],{bound:false,requestBound:!!meta.bound,videoRequest:!!meta.videoRequest},'$['+i+']',0);var after=Object.keys(state.media).length+Object.keys(state.posters).length+Object.keys(state.comments).length;if(after>before||meta.bound||meta.commentRequest||meta.videoRequest){state.relevantResponses++;emitSnapshot('graphql');}}
  function installFetch(){if(!originalFetch)return;window.fetch=function(input,init){var reqUrl=typeof input==='string'?input:(input&&input.url)||'',body=init&&init.body||'',meta=requestMeta(body);return originalFetch(input,init).then(function(resp){try{if(/graphql/i.test(reqUrl)&&resp&&resp.clone){resp.clone().text().then(function(txt){if(txt&&txt.length<=24*1024*1024)inspect(txt,meta);}).catch(function(){});}}catch(_){}return resp;});};}
  function installXHR(){if(!XHR||!originalOpen||!originalSend)return;XHR.prototype.open=function(method,url){this.__fbReelUrlV44R21R14=String(url||'');return originalOpen.apply(this,arguments);};XHR.prototype.send=function(body){var self=this,meta=requestMeta(body);try{self.addEventListener('load',function(){try{if(!/graphql/i.test(self.__fbReelUrlV44R21R14||'')||typeof self.responseText!=='string'||self.responseText.length>24*1024*1024)return;inspect(self.responseText,meta);}catch(_){}},{once:true});}catch(_){}return originalSend.apply(this,arguments);};}
  window.addEventListener('message',function(ev){if(ev.source!==window)return;var d=ev.data;if(!d||d.channel!==CONTROL)return;if(d.type==='GET_REEL_EVIDENCE')emitSnapshot('request');else if(d.type==='RESET_REEL_EVIDENCE'){ensureRoute();emitSnapshot('reset');}});
  ensureRoute();installFetch();installXHR();
  var marker=Object.freeze({version:'V44R21R28',installed:true,trust:'HOST_CONTEXT_UNTRUSTED',apiExposed:false});
  window.__FB_REEL_EVIDENCE_MAIN_V44R21R14__=marker;
  setTimeout(function(){emitSnapshot('installed');},0);
})();
